In [1]:
import pandas as pd
import numpy as np

import gensim
import os

In [23]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
story = []

for filename in os.listdir('Dataset\Game of Thrones'):

    f = open(os.path.join('Dataset\Game of Thrones', filename), encoding='latin-1')

    corpus = f.read()
    raw_sent = sent_tokenize(corpus)


    for sent in raw_sent:
        words = simple_preprocess(sent)
        filter_story = [w for w in words if w not in stop_words]
        story.append(filter_story)

In [24]:
len(story)

145020

In [25]:
story

[['game',
  'thrones',
  'book',
  'one',
  'song',
  'ice',
  'fire',
  'george',
  'martin',
  'prologue',
  'start',
  'back',
  'gared',
  'urged',
  'woods',
  'began',
  'grow',
  'dark',
  'around'],
 ['wildlings', 'dead'],
 ['dead', 'frighten'],
 ['ser', 'waymar', 'royce', 'asked', 'hint', 'smile'],
 ['gared', 'rise', 'bait'],
 ['old', 'man', 'past', 'fifty', 'seen', 'lordlings', 'come', 'go'],
 ['dead', 'dead', 'said'],
 ['business', 'dead'],
 ['dead'],
 ['royce', 'asked', 'softly'],
 ['proof'],
 ['saw', 'gared', 'said'],
 ['says', 'dead', 'proof', 'enough'],
 ['known', 'would', 'drag', 'quarrel', 'sooner', 'later'],
 ['wished', 'later', 'rather', 'sooner'],
 ['mother', 'told', 'dead', 'men', 'sing', 'songs', 'put'],
 ['wet', 'nurse', 'said', 'thing', 'royce', 'replied'],
 ['never', 'believe', 'anything', 'hear', 'woman', 'tit'],
 ['things', 'learned', 'even', 'dead'],
 ['voice', 'echoed', 'loud', 'twilit', 'forest'],
 ['page', 'long', 'ride', 'us', 'gared', 'pointed'],
 ['eig

In [26]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [27]:
model.build_vocab(story) # Extract Unique word and build Vocabulary

In [28]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

Exception ignored in: 'gensim.models.word2vec_inner.our_dot_float'


(4396605, 4579390)

In [29]:
model.wv.most_similar('daenerys')

[('stormborn', 0.9206749200820923),
 ('unburnt', 0.8782766461372375),
 ('targaryen', 0.8408263325691223),
 ('viserys', 0.8406319618225098),
 ('dorne', 0.8311087489128113),
 ('rhaella', 0.8239397406578064),
 ('elia', 0.8229907751083374),
 ('westeros', 0.8179293274879456),
 ('myrcella', 0.8142658472061157),
 ('sunspear', 0.8079185485839844)]

In [30]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [31]:
model.wv['king']

array([-0.584077  , -0.17975497,  0.12521818,  1.0825714 , -0.49640062,
       -0.11424118,  0.3878648 , -1.0024208 , -0.87224054, -0.15673286,
       -0.19494809,  0.50235075,  0.35249978, -0.11269445, -0.5461958 ,
        1.4424553 ,  2.015463  , -0.07226393, -0.48202974, -0.6414309 ,
       -0.20617038,  2.4528544 ,  0.00947656, -4.1007533 ,  1.0672249 ,
        0.4968523 , -1.1125458 ,  0.03977842, -1.0654248 ,  0.9483114 ,
       -1.4492072 ,  1.7858292 ,  0.2096535 , -0.29361153, -0.57100993,
        1.115489  , -0.7306146 , -1.6851696 , -0.25751272,  0.04258063,
        1.9381878 , -0.29189134,  0.5151764 ,  1.099626  ,  1.6007822 ,
       -0.83046144, -1.1584669 , -0.35227045,  2.0049202 ,  0.86323655,
       -2.3734837 , -0.7879643 ,  3.1152294 , -0.4317984 , -0.08754378,
        3.7294102 , -1.0204377 ,  1.4539746 ,  0.09768542,  3.3833363 ,
        1.6183656 ,  0.55188096, -1.8031265 ,  1.3688804 ,  0.09323461,
        0.05640846, -2.4636467 ,  1.8558294 ,  0.28005812, -1.05

In [32]:
model.wv['king'].shape

(100,)

In [33]:
model.wv.get_normed_vectors()

array([[-0.02865668,  0.0607347 ,  0.0357005 , ..., -0.06272503,
        -0.10039198,  0.21161723],
       [-0.20115583,  0.14584659,  0.13587485, ..., -0.10872643,
        -0.1169559 ,  0.20745286],
       [-0.0168936 ,  0.05059268, -0.03874884, ..., -0.117962  ,
         0.10526393, -0.16107099],
       ...,
       [-0.09265379,  0.03086524, -0.02867266, ..., -0.10185795,
         0.04944943,  0.15446053],
       [-0.15585175,  0.01233817,  0.18735655, ..., -0.11000991,
         0.14800972,  0.03548029],
       [-0.05305459,  0.05640624,  0.1579532 , ...,  0.00136667,
        -0.00851827, -0.10182884]], dtype=float32)

In [34]:
model.wv.get_normed_vectors().shape

(17310, 100)

In [35]:
y = model.wv.index_to_key

In [36]:
y

['said',
 'lord',
 'would',
 'one',
 'ser',
 'could',
 'man',
 'king',
 'men',
 'back',
 'well',
 'like',
 'jon',
 'father',
 'old',
 'hand',
 'even',
 'tyrion',
 'never',
 'know',
 'see',
 'made',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'long',
 'might',
 'us',
 'come',
 'face',
 'still',
 'head',
 'red',
 'way',
 'boy',
 'page',
 'must',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 'little',
 'took',
 'came',
 'though',
 'say',
 'three',
 'away',
 'dead',
 'son',
 'blood',
 'take',
 'go',
 'half',
 'make',
 'arya',
 'saw',
 'day',
 'white',
 'jaime',
 'first',
 'look',
 'want',
 'much',
 'enough',
 'sword',
 'tell',
 'girl',
 'bran',
 'great',
 'looked',
 'left',
 'knew',
 'asked',
 'gave',
 'maester',
 'called',
 'wall',
 'every',
 'heard',
 'sansa',
 'let',
 'yet',
 'went',
 'turned',
 'dany',
 'need',
 'behind',
 'around',
 'woman',
 'another',
 'snow',
 'beneath',
 'across',
 'knight',
 'keep',
 'grace',
 'found',
 'gold',
 'last',
 'cersei',
 'castle',
 '

In [20]:
len(y)

17453

In [37]:
from sklearn.decomposition import PCA

In [38]:
pca = PCA(n_components=3)

X = pca.fit_transform(model.wv.get_normed_vectors())

In [39]:
X[:5]

array([[ 0.47106898,  0.0109878 ,  0.23044866],
       [ 0.3923728 ,  0.5687641 ,  0.35794303],
       [ 0.53211915, -0.05644919, -0.30933228],
       [ 0.00983749,  0.15219244, -0.0298693 ],
       [ 0.26154715,  0.5299593 ,  0.5311125 ]], dtype=float32)

In [40]:
X.shape

(17310, 3)

In [43]:
import plotly.express as px

fig = px.scatter_3d(X[:100], x=0, y=1,z=2, color = y[:100])
fig.show()